{
 "openapi": "3.0.1",
 "info": {
  "contact": {
   "email": "bkama@atlassian.com"
  },
  "description": "Operations APIs for Jira Service Management",
  "title": "JSM Operations API",
  "version": "1"
 },
 "servers": [
  {
   "url": "https://api.atlassian.com/jsm/ops/api/{cloudId}",
   "description": "Generated server url"
  }
 ],
 "security": [
  {
   "basicAuth": []
  }
 ],
 "components": {
  "securitySchemes": {
   "basicAuth": {
    "type": "http",
    "scheme": "basic"
   },
   "OAuth2": {
    "type": "oauth2",
    "description": "OAuth2 Scopes for JSM Operations Rest API",
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "https://auth.stg.atlassian.com/authorize",
      "tokenUrl": "https://auth.stg.atlassian.com/oauth/token",
      "scopes": {
       "read:ops-alert:jira-service-management": "Read Jira Service Management operations alert data",
       "write:ops-alert:jira-service-management": "Create and manage Jira Service Management operations alerts",
       "delete:ops-alert:jira-service-management": "Delete Jira Service Management operations alert",
       "read:ops-config:jira-service-management": "Read Jira Service Management operations configuration",
       "write:ops-config:jira-service-management": "Create and manage Jira Service Management operations configuration",
       "delete:ops-config:jira-service-management": "Delete Jira Service Management operations configuration"
      }
     }
    }
   }
  }
 },
 "x-atlassian-narrative": {
  "documents": [
   {
    "title": "About",
    "anchor": "about",
    "body": "This is the reference for the Jira Service Management operations REST API.  The REST API is for developers who want to integrate Jira Service Management operations with other  applications or administrators that want to automate their workflows and processes.\n"
   },
   {
    "title": "Jira Cloud Platform APIs",
    "anchor": "jira-cloud-platform-apis",
    "body": "Jira Service Management operations, an integral part of Jira Service Management, is designed to optimize the management of your team's operations. Jira Service Management is built upon the Jira platform. As such, in Jira Service Management you have access to the Jira\nplatform REST APIs.\n\n  * [Browse the Jira platform REST APIs](/cloud/jira/platform/rest/)\n"
   },
   {
    "title": "Permissions and roles",
    "anchor": "permissions",
    "body": "Permissions control the level of a user's access to the Jira Service Management\ninstance, while roles are how the permissions are assigned to individual users.\nFor detailed information on roles and permissions, see [Permissions overview](https://support.atlassian.com/jira-service-management-cloud/docs/overview-of-jira-cloud-permissions/)\nand [Setting up service desk users](https://support.atlassian.com/jira-service-management-cloud/docs/set-up-service-desk-users-to-work-on-reques[...]"
   },
   {
    "title": "Authentication",
    "anchor": "authentication",
    "body": "### Authentication for REST API requests\n\nJira Service Management operations API supports the use of the basic authentication method. \n[Basic auth for REST APIs](https://developer.atlassian.com/cloud/jira/service-desk/jira-rest-api-basic-authentication/) for details.\n\n  ### Authentication for Forge apps\n\nFor Forge apps, [REST API scopes](https://developer.atlassian.com/cloud/jira/service-desk-ops/security/oauth-2-authorization-code-grants-3lo-for-apps/) \nare used when authen[...]"
   },
   {
    "title": "Status codes and responses",
    "anchor": "status",
    "body": "-   <span class=\"aui-lozenge aui-lozenge-success\">Status 200</span> Returned if the requested content (GET) is returned or content is updated (PUT).\n-   <span class=\"aui-lozenge aui-lozenge-success\">Status 201</span> Returned if new records are created (PUT).\n-   <span class=\"aui-lozenge aui-lozenge-success\">Status 204</span> Returned where the request may or may not have been actioned, but the outcome is as expected. For example, the schedule has been successfully removed, [...]"
   },
   {
    "title": "URL format",
    "anchor": "url",
    "body": "The Jira Service Management operations REST API uses a consistent URL pattern to access different resources. The general format is as follows: \n```\nhttps://api.atlassian.com/jsm/ops/api/{cloudId}/{version}/{domain}\n```\n - **{cloudId}** represents the unique identifier for your cloud instance. \n - **{version}** is the version of the API you want to access. Currently, only version 1 ('v1') is available.\n - **{domain}**  is the specific domain of the API you want to access. Examp[...]"
   },
   {
    "title": "Date and time format",
    "anchor": "dateTime",
    "body": "The Jira Service Management operations REST API follows the **ISO 8601** standard for representing dates and times. This consistent string format, such as '2023-12-15T15:20:25+00:00', \nis used across all API endpoints. In this format, '2023-12-15' denotes the date (**year-month-day**), 'T' is a delimiter that separates the date from the time, '15:20:25' represents the time\n(**hours:minutes:seconds**), and '+00:00' indicates the timezone offset from Coordinated Universal Time (**UT[...]"
   },
   {
    "title": "Pagination",
    "anchor": "pagination",
    "body": "The Jira Service Management operations REST API uses pagination to conserve server resources and limit the size of responses. Pagination is enforced for methods that could return a large collection. When you make a request to a paged API, the response will wrap the returned values in a JSON object with paging metadata, as follows:\n\n **Request**\n```\nhttps://api.atlassian.com/jsm/ops/api/{cloudId}/v1/{domain}?offset=0&size=10\n```\n\n **Response**\n ```json\n {\n  \"values\" : [\n[...]"
   },
   {
    "title": "Expansion",
    "anchor": "expansion",
    "body": "To simplify API responses, the Jira Service Management operations REST API uses resource expansion: the API will only return parts of the resource when explicitly requested.\nUse the `expand` query parameter to specify the list of entities that you want to be expanded, identifying each of them by name. \n\nFor example, appending `?expand=base` to a request’s URI results in the inclusion of the base timeline details in the response of schedule timeline. \nThe following URL would be u[...]"
   }
  ]
 },
 "x-common-scopes": {
  "read_alert_scopes": [
   "read:ops-alert:jira-service-management"
  ],
  "write_alert_scopes": [
   "read:ops-alert:jira-service-management",
   "write:ops-alert:jira-service-management"
  ],
  "delete_alert_scopes": [
   "read:ops-alert:jira-service-management",
   "delete:ops-alert:jira-service-management"
  ],
  "read_config_scopes": [
   "read:ops-config:jira-service-management"
  ],
  "write_config_scopes": [
   "read:ops-config:jira-service-management",
   "write:ops-config:jira-service-management"
  ],
  "delete_config_scopes": [
   "read:ops-config:jira-service-management",
   "delete:ops-config:jira-service-management"
  ],
  "read_alert": [
   {
    "basicAuth": []
   },
   {
    "OAuth2": [
     "read:ops-alert:jira-service-management"
    ]
   }
  ],
  "write_alert": [
   {
    "basicAuth": []
   },
   {
    "OAuth2": [
     "read:ops-alert:jira-service-management",
     "write:ops-alert:jira-service-management"
    ]
   }
  ],
  "delete_alert": [
   {
    "basicAuth": []
   },
   {
    "OAuth2": [
     "read:ops-alert:jira-service-management",
     "delete:ops-alert:jira-service-management"
    ]
   }
  ],
  "read_config": [
   {
    "basicAuth": []
   },
   {
    "OAuth2": [
     "read:ops-config:jira-service-management"
    ]
   }
  ],
  "write_config": [
   {
    "basicAuth": []
   },
   {
    "OAuth2": [
     "read:ops-config:jira-service-management",
     "write:ops-config:jira-service-management"
    ]
   }
  ],
  "delete_config": [
   {
    "basicAuth": []
   },
   {
    "OAuth2": [
     "read:ops-config:jira-service-management",
     "delete:ops-config:jira-service-management"
    ]
   }
  ]
 },
 "tags": [
  {
   "name": "Alerts",
   "description": "The Alerts API is designed to manage alerts which provide critical context and enable teams to manage incidents effectively. This resource represents the all contracts of alerts in Jira Service Management."
  },
  {
   "name": "Audit Logs",
   "description": "The Audit Logs API is designed to help you access the operations audit logs which capture the key changes and activities in Jira Service Management. The activities include alerting, on-call, incident management, and other operation features."
  },
  {
   "name": "Contacts",
   "description": "This resource represents the contract to create/update/delete alert notification contacts in Jira Service Management."
  },
  {
   "name": "Custom user roles"
  },
  {
   "name": "Escalations",
   "description": "Escalation policies can be used to notify multiple users/teams/schedules in order till the alert is acknowledged by someone. This resource represents the contract to create/update/delete/get of escalations in Jira Service Management."
  },
  {
   "name": "Forwarding rules",
   "description": "This resource represents the contract to create/update/delete/get of forwarding-rules in Jira Service Management. Forwarding rules are used for forwarding the incoming notification to another user."
  },
  {
   "name": "Heartbeats",
   "description": "This resource represents the contract to create/update/delete/get of heartbeats in Jira Service Management."
  },
  {
   "name": "Integrations",
   "description": "This resource represents Integrations in Jira Service Management. Use it to get, list, create, update, or delete integrations."
  },
  {
   "name": "Integration actions",
   "description": "This resource represents Integration Actions in Jira Service Management. Use it to get, list, create, update, delete or reorder of actions of an integration."
  },
  {
   "name": "Integration outgoing filters",
   "description": "This resource represents Alert Filters of an Integration in Jira Service Management. Use it to get or update alert filters of an integration."
  },
  {
   "name": "Maintenances",
   "description": "A set of rules that can be added to enable or disable multiple policies, integrations or syncs with a single entry. This resource represents the all contracts of maintenance plans in Jira Service Management."
  },
  {
   "name": "Notification rules",
   "description": "Notification rules allow users to configure notification steps that use their existing contact methods and define conditions & time constraints on them. This resource represents the contract to create/get/update/delete/list of notification-rules in Jira Service Management."
  },
  {
   "name": "Notification rule steps",
   "description": "Notification rule steps allow users to define how they want to be notified. This resource represents the all contracts of notification rule steps in Jira Service Management."
  },
  {
   "name": "Policies",
   "description": "This resource represents the contract to create/read/update/delete of Policies in Jira Service Management."
  },
  {
   "name": "Team"
  },
  {
   "name": "Team Policies",
   "description": "This resource represents the contract to create/read/update/delete of Team Policies Jira Service Management."
  },
  {
   "name": "Team roles"
  },
  {
   "name": "Routing rules",
   "description": "This resource represents the contract to create/read/update/delete of routing rules in Jira Service Management."
  },
  {
   "name": "Schedules",
   "description": "This resource represents schedules in Jira Service Management. Use it to:\n - create a new schedule. \n - list all schedules. \n - get a schedule. \n - update a schedule. \n - delete a schedule."
  },
  {
   "name": "Schedule on-calls",
   "description": "This resource represents schedule on-calls in Jira Service Management. Use it to:\n - list on-call responders on a schedule.\n - list the next on-call responders on a schedule.\n - export on-call responders on a schedule in calendar format."
  },
  {
   "name": "Schedule overrides",
   "description": "This resource represents schedule overrides in Jira Service Management. Use it to:\n - list all overrides of a schedule. \n - create a new override. \n - get an override. \n - update an override. \n - delete an override."
  },
  {
   "name": "Schedule rotations",
   "description": "This resource represents on-call schedule rotations in Jira Service Management. Use it to:\n - list all rotations of a schedule. \n - create a new rotation. \n - get a rotation. \n - update a rotation. \n - delete a rotation."
  },
  {
   "name": "Schedule timelines",
   "description": "This resource represents schedule timelines in Jira Service Management. Use it to:\n - calculate the timeline of a schedule. \n - export the timeline of a schedule in calendar format. \n"
  },
  {
   "name": "Syncs",
   "description": "This resource represents Syncs in Jira Service Management. Use it to get, list, create, update, or delete syncs."
  },
  {
   "name": "Sync actions",
   "description": "This resource represents Sync Actions in Jira Service Management. Use it to get, list, create, update, delete or reorder of actions of a sync."
  },
  {
   "name": "Sync action groups",
   "description": "This resource represents Sync Action Groups in Jira Service Management. Use it to get, list, create, update, delete or reorder of action groups of a sync."
  }
 ],
 "paths": {
  "/v1/schedules": {
   "get": {
    "tags": [
     "Schedules"
    ],
    "summary": "List schedules",
    "description": "Lists all schedules that user can view. It optionally takes two parameters - offset and size.<br> <br> **Permissions required:** Permission to access Jira Service Management; however, the list contains a schedule if: \n - the user has read-only administrative right. \n - the schedule's assigned team is one of the teams that the user belongs to. \n - the user is added to a rotation of the schedule as a responder. \n - a team is added to a rotation of the schedule as a responde[...]",
    "operationId": "listSchedules",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Schedules"
    ],
    "summary": "Create schedule",
    "description": "Creates a schedule with given properties.<br> <br> **Permissions required:** Permission to create a schedule: \n - the user has edit configuration right. \n - the user is the admin of the team that the schedule belongs to.",
    "operationId": "createSchedule",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/schedules/{id}": {
   "get": {
    "tags": [
     "Schedules"
    ],
    "summary": "Get schedule",
    "description": "Returns the details of the schedule with given id in the request. <br> <br> **Permissions required:** Permission to access to the schedule: \n - the user has read-only administrative right. \n - the schedule's assigned team is one of the teams that the user belongs to. \n - the user is added to a rotation of the schedule as a responder. \n - a team is added to a rotation of the schedule as a responder, and the user is a member of this team. \n - an escalation is added to a ro[...]",
    "operationId": "getSchedule",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Schedules"
    ],
    "summary": "Update schedule",
    "description": "Updates the schedule with given id in the request. <br> <br> **Permissions required:** Permission to update the schedule: \n - the user has edit configuration right. \n - the user is the admin of the team that the schedule belongs to.",
    "operationId": "updateSchedule",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Schedules"
    ],
    "summary": "Delete schedule",
    "description": "Deletes the schedule with given id in the request. <br> <br> **Permissions required:** Permission to delete the schedule: \n - the user has delete configuration right. \n - the user is the admin of the team that the schedule belongs to.",
    "operationId": "deleteSchedule",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "delete:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/schedules/{scheduleId}/rotations": {
   "get": {
    "tags": [
     "Schedule rotations"
    ],
    "summary": "List rotations",
    "description": "Lists all rotations of the schedule with given id in the request. It optionally takes two parameters - offset and size.<br> <br> **Permissions required:** Permission to access to the schedule: \n - the user has read-only administrative right. \n - the schedule's assigned team is one of the teams that the user belongs to. \n - the user is added to a rotation of the schedule as a responder. \n - a team is added to a rotation of the schedule as a responder, and the user is a mem[...]",
    "operationId": "listRotations",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Schedule rotations"
    ],
    "summary": "Create rotation",
    "description": "Creates a new rotation for the schedule with given id and properties.<br> <br> **Permissions required:** Permission to edit a schedule: \n - the user has edit configuration right. \n - the user is the admin of the team that the schedule belongs to.",
    "operationId": "createRotation",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/schedules/{scheduleId}/rotations/{id}": {
   "get": {
    "tags": [
     "Schedule rotations"
    ],
    "summary": "Get rotation",
    "description": "Returns the details of the rotation of a schedule with given IDs in the request. <br> <br> **Permissions required:** Permission to access to the schedule: \n - the user has read-only administrative right. \n - the schedule's assigned team is one of the teams that the user belongs to. \n - the user is added to a rotation of the schedule as a responder. \n - a team is added to a rotation of the schedule as a responder, and the user is a member of this team. \n - an escalation i[...]",
    "operationId": "getRotation",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Schedule rotations"
    ],
    "summary": "Delete rotation",
    "description": "Deletes the rotation of a schedule with given IDs in the request. <br> <br> **Permissions required:** Permission to delete the rotation: \n - the user has delete configuration right. \n - the user is the admin of the team that rotation's schedule belongs to.",
    "operationId": "deleteRotation",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "delete:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Schedule rotations"
    ],
    "summary": "Update rotation",
    "description": "Updates the rotation of a schedule with given IDs in the request. <br> <br> **Permissions required:** Permission to edit a schedule: \n - the user has edit configuration right. \n - the user is the admin of the team that the schedule belongs to.",
    "operationId": "updateRotation",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/schedules/{scheduleId}/overrides": {
   "get": {
    "tags": [
     "Schedule overrides"
    ],
    "summary": "List overrides",
    "description": "Lists all ongoing and future overrides of the schedule with given id in the request. It optionally takes two parameters - offset and size.<br> <br> **Permissions required:** Permission to access to the schedule: \n - the user has read-only administrative right. \n - the schedule's assigned team is one of the teams that the user belongs to. \n - the user is added to a rotation of the schedule as a responder. \n - a team is added to a rotation of the schedule as a responder, an[...]",
    "operationId": "listOverrides",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Schedule overrides"
    ],
    "summary": "Create override",
    "description": "Creates a new override for the schedule with given id and properties.<br> <br> **Permissions required:** Permission to create an override: \n - the user has edit configuration right. \n - the user is a member of the team that the schedule belongs to. \n - the user is adding override to themself. \n - the user exists in the schedule directly or indirectly.",
    "operationId": "createOverride",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/schedules/{scheduleId}/overrides/{alias}": {
   "get": {
    "tags": [
     "Schedule overrides"
    ],
    "summary": "Get override",
    "description": "Returns the details of the override of a schedule with given IDs in the request. <br> <br> **Permissions required:** Permission to access to the schedule: \n - the user has read-only administrative right. \n - the schedule's assigned team is one of the teams that the user belongs to. \n - the user is added to a rotation of the schedule as a responder. \n - a team is added to a rotation of the schedule as a responder, and the user is a member of this team. \n - an escalation i[...]",
    "operationId": "getOverride",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Schedule overrides"
    ],
    "summary": "Update override",
    "description": "Updates the override of a schedule with given IDs in the request.<br> <br> **Permissions required:** Permission to update an override: \n - the user has edit configuration right. \n - the user is a member of the team that the schedule belongs to. \n - the user is adding override to themself. \n - the user exists in the schedule directly or indirectly by flattening.",
    "operationId": "updateOverride",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Schedule overrides"
    ],
    "summary": "Delete override",
    "description": "Deletes the override of a schedule with given IDs in the request. <br> <br> **Permissions required:** Permission to delete the override: \n - the user is the responder of the override. \n - the user has edit configuration right. \n - the user is the admin of the team that the schedule belongs to.",
    "operationId": "deleteOverride",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "delete:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/schedules/{scheduleId}/timeline": {
   "get": {
    "tags": [
     "Schedule timelines"
    ],
    "summary": "Get schedule timeline",
    "description": "Returns the timeline of the schedule with given id in the request. The time range of the timeline can go back at most one year from today and as far as two years from today. Therefore, query parameters should be given accordingly.<br> <br> **Permissions required:** Permission to access to the schedule: \n - the user has read-only administrative right. \n - the schedule's assigned team is one of the teams that the user belongs to. \n - the user is added to a rotation of the sc[...]",
    "operationId": "getTimeline",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/schedules/{scheduleId}.ics": {
   "get": {
    "tags": [
     "Schedule timelines"
    ],
    "summary": "Export schedule timeline",
    "description": "Exports the timeline in the calendar (.ics) format for the schedule with given id in the request. The time range of the export starts from the beginning of the current month and ends one year after the start date.<br> <br> **Permissions required:** Permission to access to the schedule: \n - the user has read-only administrative right. \n - the schedule's assigned team is one of the teams that the user belongs to. \n - the user is added to a rotation of the schedule as a respo[...]",
    "operationId": "exportTimeline",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/schedules/{scheduleId}/on-calls": {
   "get": {
    "tags": [
     "Schedule on-calls"
    ],
    "summary": "List on-call responders",
    "description": "Lists the on-call responders at a specific time for the schedule with given id in the request.<br> <br> **Permissions required:** Permission to access to the schedule: \n - the user has read-only administrative right. \n - the schedule's assigned team is one of the teams that the user belongs to. \n - the user is added to a rotation of the schedule as a responder. \n - a team is added to a rotation of the schedule as a responder, and the user is a member of this team. \n - an[...]",
    "operationId": "getOnCalls",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/schedules/{scheduleId}/next-on-calls": {
   "get": {
    "tags": [
     "Schedule on-calls"
    ],
    "summary": "List next on-call responders",
    "description": "Lists the next on-call responders at a specific time for the schedule with given id in the request.<br> <br> **Permissions required:** Permission to access to the schedule: \n - the user has read-only administrative right. \n - the schedule's assigned team is one of the teams that the user belongs to. \n - the user is added to a rotation of the schedule as a responder. \n - a team is added to a rotation of the schedule as a responder, and the user is a member of this team. \n[...]",
    "operationId": "getNextOnCalls",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/schedules/on-calls/{userIdentifier}.ics": {
   "get": {
    "tags": [
     "Schedule on-calls"
    ],
    "summary": "Export on-call responders",
    "description": "Exports the on-call periods in the calendar (.ics) format for the user with given id in the request.\n \n **Permissions required:** Permission to export to the user on-calls: \n - the user exports the on-call calendar for themselves. \n - the user exports the on-call calendar for another user, and the requesting user is the admin. \n - the user exports the on-call calendar for another user, and the requesting user is the team admin in one of the teams of the requested user. \[...]",
    "operationId": "exportOnCalls",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/teams/{teamId}/escalations": {
   "get": {
    "tags": [
     "Escalations"
    ],
    "summary": "List escalations",
    "description": "Lists all escalations under given team. It optionally takes two parameters - offset and size.",
    "operationId": "listEscalation",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Escalations"
    ],
    "summary": "Create escalation",
    "description": "Creates an escalation with the given properties.",
    "operationId": "createEscalation",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/teams/{teamId}/escalations/{id}": {
   "get": {
    "tags": [
     "Escalations"
    ],
    "summary": "Get escalation",
    "description": "Gets an escalation with given id in the request.",
    "operationId": "getEscalation",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Escalations"
    ],
    "summary": "Delete escalation",
    "description": "Deletes an escalation with given id in the request.",
    "operationId": "deleteEscalation",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "delete:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Escalations"
    ],
    "summary": "Update escalation",
    "description": "Updates an escalation with given id in the request.",
    "operationId": "updateEscalation",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/logs": {
   "get": {
    "tags": [
     "Audit Logs"
    ],
    "summary": "Get audit Logs",
    "description": "This endpoint returns all operations audit logs in Jira Service Management, allowing retrieval of logs in a specified time range and  filtering based on log level and category. <br> <br> **Permissions required:** Permission to view Jira Service Management Audit logs using a JSM Org/Site/Product admin role ",
    "operationId": "listLogs",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/maintenances": {
   "get": {
    "tags": [
     "Maintenances"
    ],
    "summary": "List global maintenances",
    "description": "This endpoint is used to retrieve a list of maintenance that have been created within your organization's account in the Jira Service Management system. It optionally takes three parameters - offset, size and type.",
    "operationId": "listGlobalMaintenances",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Maintenances"
    ],
    "summary": "Create global maintenance",
    "description": "This endpoint is used to create a new maintenance which applies rules to all teams across your organization in Jira Service Management. The maintenance plan can include various rules that enable or disable multiple entities like policies, integrations or syncs. <b>Please note that integrations and syncs cannot be enabled via a maintenance plan but policies can.</b>",
    "operationId": "createGlobalMaintenance",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/maintenances/{id}": {
   "get": {
    "tags": [
     "Maintenances"
    ],
    "summary": "Get global maintenance",
    "description": "Gets an account based global maintenance with given id in the request.",
    "operationId": "getGlobalMaintenance",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Maintenances"
    ],
    "summary": "Deletes global maintenance",
    "description": "This request is used to delete a global maintenance.",
    "operationId": "deleteGlobalMaintenance",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "delete:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Maintenances"
    ],
    "summary": "Update global maintenance",
    "description": "This endpoint is used to update a global maintenance in Jira Service Management.",
    "operationId": "updateGlobalMaintenance",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/maintenances/{id}/cancel": {
   "post": {
    "tags": [
     "Maintenances"
    ],
    "summary": "Cancel global maintenance",
    "description": "This endpoint is used to stop an ongoing maintenance plan early. The functionality allows you to end the maintenance plan before the initially set end time.",
    "operationId": "cancelGlobalMaintenance",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/teams/{teamId}/maintenances": {
   "get": {
    "tags": [
     "Maintenances"
    ],
    "summary": "List team maintenances",
    "description": "This endpoint is used to retrieve a list of maintenance associated with a specific team in the Jira Service Management system. It optionally takes three parameters - offset, size and type.",
    "operationId": "listTeamMaintenances",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Maintenances"
    ],
    "summary": "Create team maintenance",
    "description": "This endpoint is used to create a new maintenance for a specific team in Jira Service Management. The maintenance plan can include various rules that enable or disable multiple entities like policies, integrations or syncs. <b>Please note that integrations and syncs cannot be enabled via a maintenance plan but policies can.</b>",
    "operationId": "createTeamMaintenance",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/teams/{teamId}/maintenances/{id}": {
   "get": {
    "tags": [
     "Maintenances"
    ],
    "summary": "Get team maintenance",
    "description": "This request is used to retrieve a specific maintenance of a specific team.",
    "operationId": "getTeamMaintenance",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Maintenances"
    ],
    "summary": "Delete team maintenance",
    "description": "Deletes a maintenance with given id in the request.",
    "operationId": "deleteTeamMaintenance",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "delete:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Maintenances"
    ],
    "summary": "Update team maintenance",
    "description": "Updates a team maintenance with given id in the request.",
    "operationId": "updateTeamMaintenance",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/teams/{teamId}/maintenances/{id}/cancel": {
   "post": {
    "tags": [
     "Maintenances"
    ],
    "summary": "Cancel team maintenance",
    "description": "This endpoint is used to stop an ongoing maintenance plan of a specific team early. The functionality allows you to end the maintenance period before the initially set end time. ",
    "operationId": "cancelTeamMaintenance",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/notification-rules/{ruleId}/steps": {
   "get": {
    "tags": [
     "Notification rule steps"
    ],
    "summary": "List notification rule steps",
    "description": "Lists all notifaction rule steps for the user. It optionally takes two parameters - offset and size.",
    "operationId": "listNotificationRuleSteps",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Notification rule steps"
    ],
    "summary": "Create notification rule step",
    "description": "Creates a notification rule step with the given properties.",
    "operationId": "createNotificationRuleStep",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/notification-rules/{ruleId}/steps/{id}": {
   "get": {
    "tags": [
     "Notification rule steps"
    ],
    "summary": "Get notification rule step",
    "description": "Gets a notification rule step with given id in the request.",
    "operationId": "getNotificationRuleStep",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Notification rule steps"
    ],
    "summary": "Delete notification rule step",
    "description": "Deletes a notification rule step with given id in the request.",
    "operationId": "deleteNotificationRuleStep",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "delete:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Notification rule steps"
    ],
    "summary": "Update notification rule step",
    "description": "Updates a notification rule step with given id in the request.",
    "operationId": "updateNotificationRuleStep",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/teams/{teamId}/roles/{identifier}": {
   "get": {
    "tags": [
     "Team roles"
    ],
    "summary": "Get Team role",
    "description": "Returns details of a team role.",
    "operationId": "getRole",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Team roles"
    ],
    "summary": "Update team role",
    "description": "Updates the details of a team role",
    "operationId": "update",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Team roles"
    ],
    "summary": "Delete a team role.",
    "description": "Deletes a team role.",
    "operationId": "delete",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "delete:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/teams/{teamId}/roles": {
   "get": {
    "tags": [
     "Team roles"
    ],
    "summary": "List Team roles",
    "description": "Returns list of team roles.",
    "operationId": "getRole",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Team roles"
    ],
    "summary": "Create team role",
    "description": "Creates a team role",
    "operationId": "create",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/roles/{identifier}": {
   "get": {
    "tags": [
     "Custom user roles"
    ],
    "summary": "Get custom user role",
    "description": "Returns details of a custom user role. \n - The user should have admin role and custom user role right.",
    "operationId": "getRole",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Custom user roles"
    ],
    "summary": "Update custom user role",
    "description": "Updates the details of a custom user role. \n - The user should have admin role and custom user role right.",
    "operationId": "update",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Custom user roles"
    ],
    "summary": "Delete custom user role.",
    "description": "Deletes a custom user role. \n - The user should have admin role and custom user role right.",
    "operationId": "delete",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "delete:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/roles/assign": {
   "post": {
    "tags": [
     "Custom user roles"
    ],
    "summary": "Assign custom user role",
    "description": "Assignes a custom user role to a user. \n - The user should have admin role and custom user role right. \n - Assignment on the admin roles can be done through Atlassian Administration.",
    "operationId": "assignCustomRole",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/roles": {
   "get": {
    "tags": [
     "Custom user roles"
    ],
    "summary": "List custom user roles",
    "description": "Returns the list of the custom user roles.  \n - The user should have admin role and custom user role right.",
    "operationId": "getRoles",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Custom user roles"
    ],
    "summary": "Create custom user role",
    "description": "Creates a new custom user role. \n - The user should have admin role and custom user role right.",
    "operationId": "createCustomRole",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/users/contacts": {
   "get": {
    "tags": [
     "Contacts"
    ],
    "summary": "List contacts",
    "description": "Returns the list of the contacts of a user.",
    "operationId": "list",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Contacts"
    ],
    "summary": "Create contact",
    "description": "Creates a new contact for a user.",
    "operationId": "create",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/users/contacts/{id}/activate": {
   "patch": {
    "tags": [
     "Contacts"
    ],
    "summary": "Activate contact",
    "description": "Activates a contact of a user.",
    "operationId": "activate",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/users/contacts/{id}/deactivate": {
   "patch": {
    "tags": [
     "Contacts"
    ],
    "summary": "Deactivate contact",
    "description": "Deactivates a contact of a user.",
    "operationId": "deactivate",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/users/contacts/{id}": {
   "get": {
    "tags": [
     "Contacts"
    ],
    "summary": "Get contact",
    "description": "Returns the details of a contact.",
    "operationId": "get",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Contacts"
    ],
    "summary": "Delete contact",
    "description": "Delete a contact of a user.",
    "operationId": "delete_1",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "delete:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Contacts"
    ],
    "summary": "Update contact",
    "description": "Update the details of a contact of a user. This method can be applied only to email contacts.",
    "operationId": "update_1",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/integrations": {
   "get": {
    "tags": [
     "Integrations"
    ],
    "summary": "List integrations",
    "description": "Returns all integrations that user can view. <br> <br> **Permissions required:** Permission to access Jira Service Management; however, the list contains an integration if: \n - the user has read-only administrative right. \n - the integration's assigned team is one of the teams that the user belongs to.",
    "operationId": "list",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Integrations"
    ],
    "summary": "Create integration",
    "description": "Creates an integration. It can be team or global integration by using teamId in the payload.\n  \n **Permissions required:** Permission to create an integration:\n - the user has edit configuration right. \n - the user is the admin of the team that the integration belongs to. \n  \n <br>*Slack* and *Microsoft Teams* types of integration are not supported for this operation.",
    "operationId": "create",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/integrations/{integrationId}/actions": {
   "get": {
    "tags": [
     "Integration actions"
    ],
    "summary": "List integration actions",
    "description": "Lists integration actions of an integration that user can view. <br> <br> **Permissions required:** Permission to get the integration action: \n - the user has read-only administrative right. \n - the integration's assigned team is one of the teams that the user belongs to.",
    "operationId": "list_1",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Integration actions"
    ],
    "summary": "Create integration action",
    "description": "Creates an integration action.<br> <br> **Permissions required:** Permission to create an integration action: \n - the user has read-only administrative right. \n - the user is the admin of the team that the integration belongs to.",
    "operationId": "create_1",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/integrations/{integrationId}/outgoing/alert-filter/main": {
   "get": {
    "tags": [
     "Integration outgoing filters"
    ],
    "summary": "Get integration alert filter",
    "description": "Returns the outgoing alert filter details of an integration. <br> <br> **Permissions required:** Permission to access to the integration outgoing alert filter: \n - the user has read-only administrative right. \n - the integration's assigned team is one of the teams that the user belongs to.",
    "operationId": "get",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Integration outgoing filters"
    ],
    "summary": "Update integration alert filter",
    "description": "Updates Integration outgoing alert filter. <br> <br> **Permissions required:** Permission to update integration alert filter:\n - the user has read-only administrative right. \n - the user is the admin of the team that the integration belongs to.",
    "operationId": "update",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/integrations/{integrationId}/actions/{id}": {
   "get": {
    "tags": [
     "Integration actions"
    ],
    "summary": "Get integration action",
    "description": "Returns the action of an integration. <br> <br> **Permissions required:** Permission to access to the integration action: \n - the user has read-only administrative right. \n - the integration's assigned team is one of the teams that the user belongs to.",
    "operationId": "get_1",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Integration actions"
    ],
    "summary": "Delete integration action",
    "description": "Deletes an integration action. <br> <br> **Permissions required:** Permission to update integration alert filter:\n - the user has read-only administrative right. \n - the user is the admin of the team that the integration belongs to.",
    "operationId": "delete",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "delete:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Integration actions"
    ],
    "summary": "Update integration action",
    "description": "Updates an integration action. <br> <br> **Permissions required:** Permission to update the integration action:\n - the user has read-only administrative right. \n - the user is the admin of the team that the integration belongs to.",
    "operationId": "update_1",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/integrations/{integrationId}/actions/{id}/order": {
   "patch": {
    "tags": [
     "Integration actions"
    ],
    "summary": "Reorder integration action",
    "description": "Reorders an integration action.  <br> <br> **Permissions required:** Permission to reorder the integration action:\n - the user has read-only administrative right. \n - the user is the admin of the team that the integration belongs to.",
    "operationId": "reorder",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/integrations/{id}": {
   "get": {
    "tags": [
     "Integrations"
    ],
    "summary": "Get integration",
    "description": "Returns the integration details. <br> <br> **Permissions required:** Permission to access to the integration: \n - the user has read-only administrative right. \n - the integration's assigned team is one of the teams that the user belongs to.",
    "operationId": "get_2",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Integrations"
    ],
    "summary": "Delete integration",
    "description": "Deletes an integration. <br> <br> **Permissions required:** Permission to delete the integration:\n - the user has read-only administrative right. \n - the user is the admin of the team that the integration belongs to.",
    "operationId": "delete_1",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "delete:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Integrations"
    ],
    "summary": "Update integration",
    "description": "Updates an integration.  <br> <br> **Permissions required:** Permission to update the integration:\n - the user has read-only administrative right. \n - the user is the admin of the team that the integration belongs to.",
    "operationId": "update_2",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/forwarding-rules": {
   "get": {
    "tags": [
     "Forwarding rules"
    ],
    "summary": "List forwarding rules",
    "description": "Lists the all forwarding rules user can view. It optionally takes three parameters - offset, size and showAll.",
    "operationId": "listForwardings",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Forwarding rules"
    ],
    "summary": "Create forwarding rule",
    "description": "Creates a forwarding rule with the given properties.",
    "operationId": "createForwarding",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/forwarding-rules/{id}": {
   "get": {
    "tags": [
     "Forwarding rules"
    ],
    "summary": "Get forwarding rule",
    "description": "Gets a forwarding rule with given id in the request.",
    "operationId": "getForwarding",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Forwarding rules"
    ],
    "summary": "Update forwarding rule",
    "description": "Updates a forwaring rule with given id in the request.",
    "operationId": "updateForwarding",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Forwarding rules"
    ],
    "summary": "Delete forwarding rule",
    "description": "Deletes a forwarding rule with given id in the request.",
    "operationId": "deleteForwarding",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "delete:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/teams/{teamId}/heartbeats": {
   "get": {
    "tags": [
     "Heartbeats"
    ],
    "summary": "List heartbeats",
    "description": "Lists the all heartbeats user can view. If a heartbeatName is passed, it filters out given heartbeat and only return given heartbeat.",
    "operationId": "listHeartbeats",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Heartbeats"
    ],
    "summary": "Create heartbeat",
    "description": "Create heartbeat request is used to define heartbeats in Jira Service Management. A heartbeat needs to be added, before sending heartbeat messages to JSM",
    "operationId": "createHeartbeat",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Heartbeats"
    ],
    "summary": "Delete heartbeat",
    "description": "Deletes the heartbeat with given name in the request.",
    "operationId": "deleteHeartbeat",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "delete:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Heartbeats"
    ],
    "summary": "Update heartbeat",
    "description": "Updates the heartbeat with the given name. Name of a heartbeat cannot be changed",
    "operationId": "updateHeartbeat",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/teams/{teamId}/heartbeats/ping": {
   "post": {
    "tags": [
     "Heartbeats"
    ],
    "summary": "Ping Heartbeat",
    "description": "Pings the heartbeat with given name. Heartbeat ping requests processed asynchronously, it does not check if the heartbeat exists or not before responding. Please note that receiving a PONG response does not necessarily mean that the heartbeat exists.",
    "operationId": "pingHeartbeat",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/notification-rules": {
   "get": {
    "tags": [
     "Notification rules"
    ],
    "summary": "List notification rules",
    "description": "Lists all notification rules for the user. It optionally takes two parameters - offset and size.",
    "operationId": "listNotificationRule",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Notification rules"
    ],
    "summary": "Create notification rule",
    "description": "Creates a notification rule with the given properties for the user.",
    "operationId": "createNotificationRule",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/notification-rules/{id}": {
   "get": {
    "tags": [
     "Notification rules"
    ],
    "summary": "Get notification rule",
    "description": "Gets a notification rule with given id in the request.",
    "operationId": "getNotificationRule",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Notification rules"
    ],
    "summary": "Delete notification rule",
    "description": "Deletes a notification rule with given id in the request.",
    "operationId": "deleteNotificationRule",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "delete:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Notification rules"
    ],
    "summary": "Update notification rule",
    "description": "Updates a notification rule with given id in the request.",
    "operationId": "updateNotificationRule",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/teams/{teamId}/routing-rules": {
   "get": {
    "tags": [
     "Routing rules"
    ],
    "summary": "List routing rules",
    "description": "Lists all routing rules of given team. It optionally takes two parameters - offset and size.",
    "operationId": "listRoutingRules",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Routing rules"
    ],
    "summary": "Create routing rule",
    "description": "Creates a routing rule with the given properties.",
    "operationId": "createRoutingRule",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/teams/{teamId}/routing-rules/{id}": {
   "get": {
    "tags": [
     "Routing rules"
    ],
    "summary": "Get routing rule",
    "description": "Gets a routing rule with given id in the request.",
    "operationId": "getRoutingRule",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Routing rules"
    ],
    "summary": "Delete routing rule",
    "description": "Deletes a routing rule with given id in the request.",
    "operationId": "deleteRoutingRule",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "delete:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Routing rules"
    ],
    "summary": "Update routing rule",
    "description": "Updates a routing rule with given id in the request.",
    "operationId": "updateRoutingRule",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/teams/{teamId}/routing-rules/{id}/change-order": {
   "patch": {
    "tags": [
     "Routing rules"
    ],
    "summary": "Change routing rule order",
    "description": "Changes routing rule's order with given id in the request.",
    "operationId": "changeRoutingRuleOrder",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/requests/{id}": {
   "get": {
    "tags": [
     "Alerts"
    ],
    "summary": "Get request status",
    "description": "Alert creation, deletion, and action requests are processed asynchronously to provide higher availability and scalability. This endpoint is used to track the status and alert details (if any) of the request whose identifier is given.",
    "operationId": "getRequestStatus",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts": {
   "get": {
    "tags": [
     "Alerts"
    ],
    "summary": "List alerts",
    "description": "This endpoint is designed to provide a comprehensive view of all alerts in your system. This API supports pagination and filtering with allowing you to customize the view based on your specific needs. More than 20000 alerts cannot be retrieved. Sum of offset and size should be lower than 20K.",
    "operationId": "listAlerts",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Alerts"
    ],
    "summary": "Create alert",
    "description": "The endpoint allows users to programmatically generate alerts with customized parameters. It integrates with existing systems to transform raw data into actionable alerts, ensuring timely notifications for incident management.",
    "operationId": "createAlert",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management",
       "write:ops-alert:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/{id}": {
   "get": {
    "tags": [
     "Alerts"
    ],
    "summary": "Get alert",
    "description": "This endpoint provides users the ability to retrieve comprehensive details of a specific alert using its unique id.",
    "operationId": "getAlertWithId",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Alerts"
    ],
    "summary": "Delete alert",
    "description": "This endpoint is utilized to delete alerts, along with the unique identifier of the alert.",
    "operationId": "deleteAlert",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management",
       "delete:ops-alert:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/alias": {
   "get": {
    "tags": [
     "Alerts"
    ],
    "summary": "Get alert by alias",
    "description": "This endpoint provides users the ability to retrieve comprehensive details of a specific alert using its unique alias as a query parameter.",
    "operationId": "getAlertWithAlias",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/{id}/acknowledge": {
   "post": {
    "tags": [
     "Alerts"
    ],
    "operationId": "ackAlert",
    "summary": "Acknowledge alert",
    "description": "This endpoint is used to acknowledge an existing alert. Acknowledging an alert indicates that it has been received and is being acted upon, preventing duplicate efforts and coordinating response actions.",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management",
       "write:ops-alert:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/{id}/assign": {
   "post": {
    "tags": [
     "Alerts"
    ],
    "operationId": "assignAlert",
    "summary": "Assign alert",
    "description": "This endpoint is used to assign an existing alert to a user or a group. Assigning an alert ensures that responsibility for addressing the alert is clearly established, promoting efficient alert management and quicker resolution times. It is a crucial operation for coordinating incident response efforts effectively.",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management",
       "write:ops-alert:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/{id}/responders": {
   "post": {
    "tags": [
     "Alerts"
    ],
    "operationId": "addResponder",
    "summary": "Add responder to alert",
    "description": "This endpoint is used to assign a responder to an existing alert. The responder is the individual or team responsible for addressing the alert. This operation streamlines the alert management process by ensuring that alerts are directed to the correct parties for timely resolution.",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management",
       "write:ops-alert:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/{id}/extra-properties": {
   "post": {
    "tags": [
     "Alerts"
    ],
    "summary": "Add extra properties to alert",
    "description": "This endpoint is used to enrich existing alerts with additional information to provide more detailed context.",
    "operationId": "addExtraPropertyToAlert",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management",
       "write:ops-alert:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Alerts"
    ],
    "summary": "Delete extra properties from alert",
    "description": "This endpoint is used to delete the multiple extra properties.",
    "operationId": "deleteExtraPropertyFromAlert",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management",
       "delete:ops-alert:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/{id}/tags": {
   "post": {
    "tags": [
     "Alerts"
    ],
    "operationId": "addTags",
    "summary": "Add tags to alert",
    "description": "This endpoint is used to add tags to an existing alert. Tags provide a means to categorize and manage alerts more effectively, enabling quick identification and sorting of related alerts based on the assigned tags.",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management",
       "write:ops-alert:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Alerts"
    ],
    "operationId": "deleteTags",
    "summary": "Delete tags from alert",
    "description": "This endpoint is used to remove tags from an existing alert. This operation allows for the modification of alert categorization and can aid in the management process by enabling alerts to be unlinked from certain categories or groups, as represented by their tags.",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management",
       "delete:ops-alert:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/{id}/close": {
   "post": {
    "tags": [
     "Alerts"
    ],
    "operationId": "closeAlert",
    "summary": "Close alert",
    "description": "This endpoint is used to close an existing alert. Closing an alert indicates that the issue has been resolved and no further action is necessary. This operation is essential for maintaining an accurate overview of the operational status and for ensuring that only active, unresolved issues remain open.",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management",
       "write:ops-alert:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/{id}/escalate": {
   "post": {
    "tags": [
     "Alerts"
    ],
    "operationId": "escalateAlert",
    "summary": "Escalate alert to next",
    "description": "This endpoint is used to escalate an existing alert. Escalation triggers the defined escalation policies which could involve notifying additional users or teams, or increasing the frequency of notifications for the alert. This operation is particularly useful in situations where an alert requires urgent attention or has not been addressed within a certain timeframe according to the pre-set escalation paths.",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management",
       "write:ops-alert:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/{id}/action": {
   "post": {
    "tags": [
     "Alerts"
    ],
    "operationId": "executeAlertAction",
    "summary": "Execute custom action",
    "description": "This endpoint is used to execute custom actions on an existing alert. Custom actions allow for more flexible and specific responses to alerts, including integrations with external systems or triggering complex workflows. This operation is a powerful tool for extending the capabilities of the alert management process beyond predefined actions.",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management",
       "write:ops-alert:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/{id}/snooze": {
   "post": {
    "tags": [
     "Alerts"
    ],
    "operationId": "snoozeAlert",
    "summary": "Snooze alert",
    "description": "This endpoint is used to snooze an existing alert. The snooze operation temporarily silences the alert, preventing it from triggering notifications for a specified period. This is particularly useful for managing alerts that require attention at a later time or to reduce noise from non-critical alerts.",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management",
       "write:ops-alert:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/{id}/unacknowledge": {
   "post": {
    "summary": "Unacknowledge alert",
    "tags": [
     "Alerts"
    ],
    "operationId": "unackAlert",
    "description": "This endpoint is used to set the 'acknowledged' property of an existing alert as 'false', effectively marking it's status as 'open'. This allows for better tracking and management of alerts by indicating that an alert has not yet been acknowledged or addressed.",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management",
       "write:ops-alert:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/{id}/notes": {
   "get": {
    "tags": [
     "Alerts"
    ],
    "operationId": "getAlertNotes",
    "description": "This endpoint is used to retrieve a list of notes for a specified alert. Notes provide additional information or context about an alert, helping to enhance the understanding and management of alerts.",
    "summary": "List alert notes",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Alerts"
    ],
    "operationId": "addAlertNote",
    "description": "This endpoint is used to add a note to an existing alert.",
    "summary": "Add alert note",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management",
       "write:ops-alert:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/{alertId}/notes/{id}": {
   "patch": {
    "tags": [
     "Alerts"
    ],
    "operationId": "updateAlertNote",
    "description": "This endpoint is used to update a note associated with a specific alert.",
    "summary": "Update alert note",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management",
       "write:ops-alert:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Alerts"
    ],
    "operationId": "deleteAlertNote",
    "description": "This endpoint is used to delete a note from an existing alert.",
    "summary": "Delete alert note",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management",
       "delete:ops-alert:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/{id}/priority": {
   "patch": {
    "tags": [
     "Alerts"
    ],
    "summary": "Update alert priority",
    "description": "This endpoint is used to modify the priority level of an existing alert. This endpoint allows for dynamic control over alert urgency. This aids in effective incident management by ensuring the most critical issues are addressed first.",
    "operationId": "updateAlertPriority",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management",
       "write:ops-alert:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/{id}/message": {
   "patch": {
    "tags": [
     "Alerts"
    ],
    "summary": "Update alert message",
    "description": "This endpoint is used to update the message of an existing alert. This endpoint plays a crucial role in ensuring that alert messages remain accurate and up-to-date, aiding in the effective management and resolution of incidents.",
    "operationId": "updateAlertMessage",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management",
       "write:ops-alert:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/{id}/description": {
   "patch": {
    "tags": [
     "Alerts"
    ],
    "summary": "Update alert description",
    "description": "This endpoint is used to update the description of an existing alert. This endpoint plays a crucial role in ensuring that team members have the most current details for incident response.",
    "operationId": "updateAlertDescription",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management",
       "write:ops-alert:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/{id}/logs": {
   "get": {
    "tags": [
     "Alerts"
    ],
    "summary": "List alert logs",
    "description": "This endpoint is used to retrieve a paginated list of alert logs which provides users to obtain a comprehensive record of alert activities. This includes alert creation, acknowledgment, assignment, and closure details. This endpoint is crucial for audit purposes, incident reviews, and enhancing the overall incident management process by providing complete visibility into alert history.",
    "operationId": "getAlertLogs",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-alert:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/syncs": {
   "get": {
    "tags": [
     "Syncs"
    ],
    "summary": "List syncs",
    "description": "Lists syncs according to the provided filters.\n- The user should have view permission for syncs.",
    "operationId": "list",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Syncs"
    ],
    "summary": "Create sync",
    "description": "Creates a sync for syncing alerts created and issues in a selected project. \n- The user should have sync creation permission.",
    "operationId": "createSync",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/syncs/{id}": {
   "get": {
    "tags": [
     "Syncs"
    ],
    "summary": "Get sync",
    "description": "Returns the sync.",
    "operationId": "getSync",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Syncs"
    ],
    "summary": "Delete sync",
    "description": "Deletes a sync. \n- The user should have delete permission for sync.",
    "operationId": "deleteSync",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "delete:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Syncs"
    ],
    "summary": "Update sync",
    "description": "Updates a sync. \n- The user should have edit permission for sync.",
    "operationId": "updateSync",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/syncs/{syncId}/actions": {
   "get": {
    "tags": [
     "Sync actions"
    ],
    "summary": "List sync actions",
    "description": "Lists sync actions of a sync",
    "operationId": "list_1",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Sync actions"
    ],
    "summary": "Create sync action",
    "description": "Creates a sync action",
    "operationId": "create",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/syncs/{syncId}/actions/{id}": {
   "get": {
    "tags": [
     "Sync actions"
    ],
    "summary": "Get sync action",
    "description": "Gets a sync action. ",
    "operationId": "get",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Sync actions"
    ],
    "summary": "Delete sync action",
    "description": "Deletes a sync action.",
    "operationId": "delete",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "delete:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Sync actions"
    ],
    "summary": "Update sync action",
    "description": "Updates a sync action.",
    "operationId": "update",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/syncs/{syncId}/actions/{id}/order": {
   "patch": {
    "tags": [
     "Sync actions"
    ],
    "summary": "Reorder sync action",
    "description": "Reorders a sync action. ",
    "operationId": "reorder",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/syncs/{syncId}/action-groups": {
   "get": {
    "tags": [
     "Sync action groups"
    ],
    "summary": "List sync action groups",
    "description": "Lists sync action groups of a sync",
    "operationId": "list_2",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Sync action groups"
    ],
    "summary": "Create sync action group",
    "description": "Creates a sync action group",
    "operationId": "create_1",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/syncs/{syncId}/action-groups/{id}": {
   "get": {
    "tags": [
     "Sync action groups"
    ],
    "summary": "Get sync action group",
    "description": "Gets a sync action group. ",
    "operationId": "get_1",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Sync action groups"
    ],
    "summary": "Delete sync action group",
    "description": "Deletes a sync action group.",
    "operationId": "delete_1",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "delete:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Sync action groups"
    ],
    "summary": "Update sync action group",
    "description": "Updates a sync action group.",
    "operationId": "update_1",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/syncs/{syncId}/action-groups/{id}/order": {
   "patch": {
    "tags": [
     "Sync action groups"
    ],
    "summary": "Reorder sync action group",
    "description": "Reorders a sync action group. ",
    "operationId": "reorder_1",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/policies": {
   "get": {
    "tags": [
     "Policies"
    ],
    "summary": "List global alert policies",
    "description": "List global alert policies",
    "operationId": "listGlobalPolicies",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Policies"
    ],
    "summary": "Create global alert policy",
    "description": "Create global alert policy",
    "operationId": "createGlobalPolicy",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/policies/{policyId}": {
   "get": {
    "tags": [
     "Policies"
    ],
    "summary": "Get global alert policy",
    "description": "Get global alert policy",
    "operationId": "getGlobalPolicies",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Policies"
    ],
    "summary": "Put global alert policy",
    "description": "Put global alert policy",
    "operationId": "putGlobalPolicies",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Policies"
    ],
    "summary": "Delete global alert policy",
    "description": "Delete global alert policy",
    "operationId": "deleteGlobalPolicies",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/policies/{policyId}/change-order": {
   "post": {
    "tags": [
     "Policies"
    ],
    "summary": "Change the order of global alert policy",
    "description": "Change the order of global alert policy",
    "operationId": "createGlobalPolicy",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/policies/{policyId}/enable": {
   "post": {
    "tags": [
     "Policies"
    ],
    "summary": "Enable the global alert policy",
    "description": "Enable the global alert policy",
    "operationId": "enableGlobalPolicy",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/alerts/policies/{policyId}/disable": {
   "post": {
    "tags": [
     "Policies"
    ],
    "summary": "Disable the global alert policy",
    "description": "Disable the global alert policy",
    "operationId": "disableGlobalPolicy",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/teams/{teamId}/policies": {
   "get": {
    "tags": [
     "Team Policies"
    ],
    "summary": "List team policies",
    "description": "List team policies",
    "operationId": "listTeamPolicies",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Team Policies"
    ],
    "summary": "Create team policy",
    "description": "Create team policy",
    "operationId": "putTeamPolicies",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/teams/{teamId}/policies/{policyId}": {
   "get": {
    "tags": [
     "Team Policies"
    ],
    "summary": "Get team policy",
    "description": "Get team policy",
    "operationId": "getTeamPolicies",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Team Policies"
    ],
    "summary": "Put team policy",
    "description": "Put team policy",
    "operationId": "putTeamPolicies",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Team Policies"
    ],
    "summary": "Delete global alert policy",
    "description": "Delete global alert policy",
    "operationId": "deleteGlobalPolicies",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/teams/{teamId}/policies/{policyId}/change-order": {
   "post": {
    "tags": [
     "Team Policies"
    ],
    "summary": "Change the order of team policy",
    "description": "Change the order of team policy",
    "operationId": "createGlobalPolicy",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/teams/{teamId}/policies/{policyId}/enable": {
   "post": {
    "tags": [
     "Team Policies"
    ],
    "summary": "Enable the team policy",
    "description": "Enable the team policy",
    "operationId": "enableGlobalPolicy",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/teams/{teamId}/policies/{policyId}/disable": {
   "post": {
    "tags": [
     "Team Policies"
    ],
    "summary": "Disable the global alert policy",
    "description": "Disable the global alert policy",
    "operationId": "disableGlobalPolicy",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/teams/{teamId}/enable-ops": {
   "post": {
    "tags": [
     "Team"
    ],
    "summary": "Enable Operations in team",
    "operationId": "enableOperations",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/teams/{teamId}/requests/{requestId}": {
   "get": {
    "tags": [
     "Team"
    ],
    "summary": "Get status of a team request",
    "operationId": "getTeamRequestStatus",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/teams": {
   "get": {
    "tags": [
     "Team"
    ],
    "summary": "List teams",
    "description": "Lists operations teams based on the user's role. If the user has admin rights, all teams are listed; otherwise, only the teams the user is a member of are shown.",
    "operationId": "getTeams",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ]
   }
  },
  "/v1/jec/channels": {
   "get": {
    "tags": [
     "JEC"
    ],
    "summary": "List JEC channels",
    "description": "Lists JEC channels according to the provided filters.\n- The user should have view permission for JEC",
    "operationId": "listJecChannel",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ],
    "x-experimental": true
   },
   "post": {
    "tags": [
     "JEC"
    ],
    "summary": "Create JEC Channel",
    "description": "Create JEC Channel",
    "operationId": "createJecChannel",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ],
    "x-experimental": true
   }
  },
  "/v1/jec/channels/{id}": {
   "get": {
    "tags": [
     "JEC"
    ],
    "summary": "Get JEC channel",
    "description": "Returns JEC channel",
    "operationId": "getJecChannel",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management"
      ]
     }
    ],
    "x-experimental": true
   },
   "delete": {
    "tags": [
     "JEC"
    ],
    "summary": "Delete JEC channel",
    "description": "Delete JEC channel",
    "operationId": "deleteJecChannel",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "delete:ops-config:jira-service-management"
      ]
     }
    ],
    "x-experimental": true
   }
  },
  "/v1/jec/action": {
   "post": {
    "tags": [
     "JEC"
    ],
    "summary": "Send JEC Action",
    "description": "Send JEC Channel Action",
    "operationId": "sendJecAction",
    "security": [
     {
      "basicAuth": []
     },
     {
      "OAuth2": [
       "read:ops-config:jira-service-management",
       "write:ops-config:jira-service-management"
      ]
     }
    ],
    "x-experimental": true
   }
  }
 }
}